name: Security Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan-for-secrets:
    name: Block secrets and credentials from merging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan diff for secrets
        run: |
          git fetch origin ${{ github.base_ref }}
          DIFF=$(git diff origin/${{ github.base_ref }}...HEAD)

          FOUND=false

          # High-confidence secret patterns
          patterns=(
            'sk-[a-zA-Z0-9]{20,}'                  # OpenAI API key
            'AKIA[0-9A-Z]{16}'                       # AWS access key
            'AIza[0-9A-Za-z\-_]{35}'                # Google API key
            'ghp_[a-zA-Z0-9]{36}'                   # GitHub personal access token
            'xoxb-[0-9]+-[0-9]+-[a-zA-Z0-9]+'      # Slack bot token
            'xoxp-[0-9]+-[0-9]+-[a-zA-Z0-9]+'      # Slack user token
            'xapp-[0-9]+-[a-zA-Z0-9]+'              # Slack app token
            'BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY' # Private keys
            'password\s*=\s*["\x27][^"\x27]{6,}'    # Hardcoded passwords
            'secret\s*=\s*["\x27][^"\x27]{8,}'      # Hardcoded secrets
            'token\s*=\s*["\x27][^"\x27]{10,}'      # Hardcoded tokens
          )

          for pattern in "${patterns[@]}"; do
            if echo "$DIFF" | grep -qP "$pattern" 2>/dev/null; then
              echo "SECURITY: Possible secret detected matching pattern: $pattern"
              FOUND=true
            fi
          done

          if [ "$FOUND" = "true" ]; then
            echo ""
            echo "SECURITY REVIEW FAILED"
            echo "One or more potential secrets were detected in this PR."
            echo ""
            echo "Required actions:"
            echo "  1. Remove the secret from the code"
            echo "  2. If it was committed: rotate it immediately (assume it is compromised)"
            echo "  3. Use environment variables instead: os.getenv('MY_SECRET')"
            echo "  4. Add the variable name to .env.example without a value"
            echo ""
            echo "If this is a false positive, add a comment above the line:"
            echo "  # nosec: not a real credential, this is [explanation]"
            exit 1
          fi

          echo "Security scan passed — no secrets detected."

      - name: Check for PII patterns
        run: |
          git fetch origin ${{ github.base_ref }}
          DIFF=$(git diff origin/${{ github.base_ref }}...HEAD)

          # PII patterns in test/example data
          pii_patterns=(
            '[0-9]{3}-[0-9]{2}-[0-9]{4}'       # SSN pattern
            '\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b' # Email addresses
          )

          for pattern in "${pii_patterns[@]}"; do
            matches=$(echo "$DIFF" | grep -iP "$pattern" | grep -v "example.com" | grep -v "test@" | grep -v "# nosec" || true)
            if [ -n "$matches" ]; then
              echo "WARNING: Possible PII detected. Review before merging:"
              echo "$matches"
            fi
          done

          echo "PII scan complete."
